language: java
env:
  global:
    - TERM=dumb
    - secure: "NRMBQUZgJoLTst3LMMvGQSbGkOMCnDFXMIC31qnyPjWoS3uZ5tRpLvRXIB6wjY23vd6fRFOZ5KBguDVdwxnn9mo4FxCF3lz5BLLmZVeyRaNM1SYJ/lqOJyx0KO0EuZIYtGAUODrt1g6YdRMeW0searnofTX/bw47Dg9ZFsoKSvE="
    - secure: "Q2jUnjY9xu2p3awoYA0nEukNKHKgaVTy3uKfnpIl0UMbJOTKzoxu+6qEHMNe6BaA7uhA1bYybaViS2HbXZHYhVaNoaJDDIflsY0ijvCRMfQMY1eu2/0yIm1l/bZpS5qEB/DG1mseuj0Rh+UpKvOnK/PViKgNM7vZLLb3DQ3ngZI="
install: 
  - "./gradlew clean test build publish publishBintray"